name: CI/CD – Cloud Run (Dev → Prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY: banking-repo
  IMAGE_NAME: banking-app

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    outputs:
      IMAGE_VERSION: ${{steps.version.outputs.version}}
      BASE_IMAGE: ${{steps.build_push.outputs.base_image}}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
      
      - name: Normalize env vars
        run: |
          echo "PROJECT_ID=$(echo "$PROJECT_ID" | xargs)" >> $GITHUB_ENV
          echo "REGION=$(echo "$REGION" | xargs)" >> $GITHUB_ENV  
          

      - name: Set image version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="$(date +%Y.%m.%d)-${GITHUB_RUN_NUMBER}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

           

      # - name: Build and Push
      #   run: |
      #     IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
      #     echo "Building $IMAGE"
      #     docker build -t "$IMAGE" .
      #     docker push "$IMAGE"

      - name: Build and Push
        id: build_push
        run: |
          IMAGE_BASE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME"
          echo "base_image=$IMAGE_BASE" >> $GITHUB_OUTPUT
          echo "IMAGE_BASE is : $IMAGE_BASE" \
          echo "VERSION is: $VERSION" \
          
          docker build \
            -t "$IMAGE_BASE:$VERSION" \
            -t "$IMAGE_BASE:sha-${GITHUB_SHA::7}" \
            .

          docker push "$IMAGE_BASE:$VERSION"
          docker push "$IMAGE_BASE:sha-${GITHUB_SHA::7}"
          

  deploy-dev:
      name: Deploy to DEV
      runs-on: ubuntu-latest
      needs: build
      environment: dev

      steps:
        - uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

        - uses: google-github-actions/setup-gcloud@v2

        - name: Normalize env vars
          run: |
            echo "PROJECT_ID=$(echo "$PROJECT_ID" | xargs)" >> $GITHUB_ENV
            echo "REGION=$(echo "$REGION" | xargs)" >> $GITHUB_ENV        


        # - name: Set image
        #   run: |
        #     IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
        #     echo "IMAGE=$IMAGE" >> $GITHUB_ENV

        - name: Deploy DEV
          run: |

            echo "BASE_IMAGE is ${{needs.build.outputs.BASE_IMAGE}}" \
            echo "IMAGE_VERSION is ${{needs.build.outputs.IMAGE_VERSION}}" \
            
            gcloud run deploy banking-app-dev \
              --image "${{needs.build.outputs.BASE_IMAGE}}:${{needs.build.outputs.IMAGE_VERSION}}" \
              --region $REGION \
              --platform managed \
              --allow-unauthenticated \
              --max-instances=1


  # deploy-prod:
  #   name: Deploy to PROD
  #   runs-on: ubuntu-latest
  #   needs: deploy-dev
  #   environment: production

  #   steps:
  #     - uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  #     - uses: google-github-actions/setup-gcloud@v2

  #     - name: Normalize env vars
  #       run: |
  #           echo "PROJECT_ID=$(echo "$PROJECT_ID" | xargs)" >> $GITHUB_ENV
  #           echo "REGION=$(echo "$REGION" | xargs)" >> $GITHUB_ENV

  #     - name: Set image
  #       run: |
  #         IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
  #         echo "IMAGE=$IMAGE" >> $GITHUB_ENV

  #     - name: Deploy PROD
  #       run: |
  #         gcloud run deploy banking-app-prod \
  #           --image "$IMAGE" \
  #           --region $REGION \
  #           --platform managed \
  #           --allow-unauthenticated \
  #           --max-instances=1
